# Generated by Django 2.1.3 on 2018-11-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20181104_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
