# Generated by Django 2.1.3 on 2018-11-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20181104_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type_id',
            new_name='asset_type',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='location_id',
            new_name='location',
        ),
    ]
